### ISSUE TITLE
Connection to DB

### ISSUE THREAD

**Issue by bnouhanna** [coatyio/coaty-examples#17]
I tried to run the hello-world example (js) as specified in the README.md on my windows 10 laptop. I installed PostgreSQL 11 with the default username and password. The example runs as expected; however, I can't see the newly created DB (_DB_NAME = "helloworld_db"_) on PGAdmin 4 UI nor on the SQL shell. I added _shouldPersistLocalSnapshots: true;_ to the _HistorianController_ and added the port on functions:  _getConnectionString()_ and _getAdminConnectionString()_ (following this [link)](https://coatyio.github.io/coaty-js/api/classes/historiancontroller.html#logdebug) but still, the DB doesn't seem to be created.  
My question is: do you have any idea why the DB is not created?

**Comment by ffa500** [comment]
I assume the superuser/admin name or password which is requested when installing
Postgres on Windows doesn't match the defaults defined in the example's database
configuration.

Whenever the Coaty service or monitor agent is started, it tries to create a new
database user named "helloworld_user" and a new database called "helloworld_db",
if these don't exist yet. To create such a user and database, you have to
specify an **existing** Postgres account with superuser privileges in the
database configuration file "src/shared/db.ts" in function
`getAdminConnectionString()`. For example, if your PG superuser account is named
"foo" and its password is "bar", you should specify the admin connection string
as `postgres://foo:bar@localhost/postgres`.

To confirm my assumption, please check the following :

* When starting the service agent, a message should be logged: `Failed to
  initialize database`.
* When starting the monitor agent, a message should be logged: `Failed to
  initialize monitor`.
* In pgAdmin4 UI, under "Servers > PostgreSQL 11 > Login/Group Roles" there
  should be **no** user named "helloworld_user".

If this is the case, proceed as follows:

* In pgAdmin4 UI, under "Servers > PostgreSQL 11 > Login/Group Roles" is there a
  user named "postgres" with superuser privilege and all other privileges
  enabled (click on user name and select "Properties" tab in the right view)? Is
  the password of this user "postgres" (as you specified when installing
  Postgres)?
* If not, your superuser account has been set up with different credentials.
  Create a new superuser in pgAdmin 4 with all privileges enabled and specify
  its name and password in the admin connection string.
* Next, rebuild the helloworld example with the changed database settings by
  executing `npm run build`.
* Now, the service and monitor agents shouldn't log failure message anymore.
* After the whole system has been started (broker, service, monitor, client),
  the client agent should log messages regarding SNAPSHOTS retrieved from the
  Postgres DB (by the service) for EVERY task it has carried out. Client output
  should look like this:

  ```
    <- QUERY      | Snapshots by parentObjectId: Hello World Task 3
    -> RETRIEVE   | Snapshots by parentObjectId: Hello World Task 3
    #############################
    # Snapshots retrieved 6
    # timestamp: 1586187719346  assigneeObjectId: 78560b65-6dc5-4427-b279-aeacb76428aa  status: Done
    # timestamp: 1586187711716  assigneeObjectId: 78560b65-6dc5-4427-b279-aeacb76428aa  status: InProgress
    # timestamp: 1586187711709  assigneeObjectId: 78560b65-6dc5-4427-b279-aeacb76428aa  status: Pending
    # timestamp: 1586187711707  assigneeObjectId: 78560b65-6dc5-4427-b279-aeacb76428aa  status: Pending
    # timestamp: 1586187709688  assigneeObjectId: -                                     status: Request
    # timestamp: 1586187709682  assigneeObjectId: -                                     status: Request
    #############################
  ```

Note that it is important to rebuild the application after you change the
database config settings.

BTW: You should not need to specify a port in the admin connection string if
your Postgres server is running on your local host.

BTW: By default, all task snapshots are persisted by the TaskSnapshotController: The property `shouldPersistLocalSnapshots` is already
set in the controller configuration (see line #51 in "src/service/agent.ts").

Hope this helps.

**Comment by bnouhanna** [comment]
It is working now thanks for the comments; it helped. 
The issue was that I had two versions of PostgreSQL 10 and 11 installed on my machine. The hello-world example was creating a DB in the PostgreSQL 10 while I was looking in PostgreSQL 11.
